import type { Metadata } from "next";
import { ThemeSwitcher } from "@/components/theme-switcher";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-prodiver";
import { LocaleSelector } from "gt-next/client";
import { GTProvider } from "gt-next";
import { getLocale } from "gt-next/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="bg-[linear-gradient(to_right,#80808033_1px,transparent_1px),linear-gradient(to_bottom,#80808033_1px,transparent_1px)] bg-[size:70px_70px] min-h-dvh flex flex-col overflow-hidden">
        <GTProvider>
          <ThemeProvider attribute="class" disableTransitionOnChange>
            <header className="bg-background border-b-border border-b-4 h-14 flex items-center justify-between">
              <h1 className="text-xl uppercase text-foreground font-heading pl-4">Titulo</h1>
              <div className="flex self-stretch">
                <div className="border-l-4 px-2 flex items-center">
                  <LocaleSelector />
                </div>
                <ThemeSwitcher />
              </div>
            </header>
            <main className="p-4 grow flex flex-col">
              {children}
            </main>
          </ThemeProvider>
        </GTProvider>
      </body>
    </html>
  );
}
