import { Tag } from "./types";

export const tags: Tag[] = [
    {
        id: "html-original",
        name: "html",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "head", limit: 1 },
            { name: "body", limit: 1 },
        ],
    },
    {
        id: "head-original",
        name: "head",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "title", limit: 1 },
            { name: "meta", limit: null },
            { name: "link", limit: null },
            { name: "style", limit: null },
            { name: "script", limit: null },
        ],
    },
    {
        id: "body-original",
        name: "body",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "header", limit: 1 },
            { name: "main", limit: 1 },
            { name: "footer", limit: 1 },
            { name: "div", limit: null },
            { name: "p", limit: null },
            { name: "h1", limit: 1 },
            { name: "h2", limit: null },
            { name: "h3", limit: null },
            { name: "ul", limit: null },
            { name: "ol", limit: null },
            { name: "section", limit: null },
            { name: "article", limit: null },
            { name: "nav", limit: 1 },
            { name: "script", limit: null },
        ],
    },
    {
        id: "title-original",
        name: "title",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "meta-original",
        name: "meta",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "link-original",
        name: "link",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "style-original",
        name: "style",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "script-original",
        name: "script",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "header-original",
        name: "header",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "h1", limit: 1 },
            { name: "nav", limit: 1 },
            { name: "div", limit: null },
        ],
    },
    {
        id: "main-original",
        name: "main",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "section", limit: null },
            { name: "article", limit: null },
            { name: "div", limit: null },
        ],
    },
    {
        id: "footer-original",
        name: "footer",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "p", limit: null },
            { name: "ul", limit: 1 },
            { name: "div", limit: null },
        ],
    },
    {
        id: "div-original",
        name: "div",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "p", limit: null },
            { name: "span", limit: null },
            { name: "img", limit: null },
            { name: "ul", limit: null },
            { name: "h2", limit: null },
            { name: "section", limit: null },
        ],
    },
    {
        id: "p-original",
        name: "p",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "span", limit: null },
            { name: "a", limit: null },
            { name: "strong", limit: null },
            { name: "em", limit: null },
            { name: "br", limit: null },
        ],
    },
    {
        id: "span-original",
        name: "span",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "strong", limit: null },
            { name: "em", limit: null },
            { name: "a", limit: null },
        ],
    },
    {
        id: "a-original",
        name: "a",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "span", limit: null },
            { name: "strong", limit: null },
            { name: "em", limit: null },
        ],
    },
    {
        id: "strong-original",
        name: "strong",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "em", limit: null },
        ],
    },
    {
        id: "em-original",
        name: "em",
        hasChildren: true,
        children: [],
        possibleChildren: [],
    },
    {
        id: "ul-original",
        name: "ul",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "li", limit: null },
        ],
    },
    {
        id: "ol-original",
        name: "ol",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "li", limit: null },
        ],
    },
    {
        id: "li-original",
        name: "li",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "span", limit: null },
            { name: "a", limit: null },
            { name: "p", limit: null },
        ],
    },
    {
        id: "img-original",
        name: "img",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "br-original",
        name: "br",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "form-original",
        name: "form",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "input", limit: null },
            { name: "label", limit: null },
            { name: "textarea", limit: null },
            { name: "button", limit: null },
            { name: "select", limit: null },
            { name: "div", limit: null },
        ],
    },
    {
        id: "input-original",
        name: "input",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "label-original",
        name: "label",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "span", limit: null },
            { name: "input", limit: 1 },
        ],
    },
    {
        id: "textarea-original",
        name: "textarea",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "button-original",
        name: "button",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "span", limit: null },
        ],
    },
    {
        id: "select-original",
        name: "select",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "option", limit: null },
        ],
    },
    {
        id: "option-original",
        name: "option",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "section-original",
        name: "section",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "h2", limit: 1 },
            { name: "p", limit: null },
            { name: "div", limit: null },
        ],
    },
    {
        id: "article-original",
        name: "article",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "h2", limit: 1 },
            { name: "p", limit: null },
            { name: "div", limit: null },
        ],
    },  
];
