import { Tag } from "./types";

export const tags: Tag[] = [
    {
        id: "html-original",
        name: "html",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "head", limit: 1 },
            { name: "body", limit: 1 },
        ],
    },
    {
        id: "head-original",
        name: "head",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "title", limit: 1 },
            { name: "meta", limit: null },
            { name: "link", limit: null },
            { name: "style", limit: null },
            { name: "script", limit: null },
        ],
    },
    {
        id: "body-original",
        name: "body",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "header", limit: 1 },
            { name: "main", limit: 1 },
            { name: "footer", limit: 1 },
            { name: "div", limit: null },
            { name: "p", limit: null },
            { name: "h1", limit: 1 },
            { name: "h2", limit: null },
            { name: "h3", limit: null },
            { name: "ul", limit: null },
            { name: "ol", limit: null },
            { name: "section", limit: null },
            { name: "article", limit: null },
            { name: "nav", limit: 1 },
            { name: "script", limit: null },
        ],
    },
    {
        id: "title-original",
        name: "title",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "meta-original",
        name: "meta",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "link-original",
        name: "link",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "style-original",
        name: "style",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "script-original",
        name: "script",
        hasChildren: false,
        children: [],
        possibleChildren: [],
    },
    {
        id: "header-original",
        name: "header",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "h1", limit: 1 },
            { name: "nav", limit: 1 },
            { name: "div", limit: null },
        ],
    },
    {
        id: "main-original",
        name: "main",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "section", limit: null },
            { name: "article", limit: null },
            { name: "div", limit: null },
        ],
    },
    {
        id: "footer-original",
        name: "footer",
        hasChildren: true,
        children: [],
        possibleChildren: [
            { name: "p", limit: null },
            { name: "ul", limit: 1 },
            { name: "div", limit: null },
        ],
    },
];
